title: 'Side Project'
sections:
  main:
    display: Main
    fields:
      header_menu:
        type: replicator
        display: 'Header Menu'
        sets:
          header_link:
            display: 'Header Link'
            fields:
              header_link:
                fieldset: header_menu
                type: partial
                display: 'Header Link'
      image:
        sets:
          image:
            display: Image
            fields:
              image:
                fieldset: image
                type: partial
                display: Image
        type: replicator
        display: Image
      large_text_heading:
        buttons:
          - h2
          - h3
          - bold
          - italic
          - unorderedlist
          - orderedlist
          - removeformat
          - quote
          - anchor
        style: sans
        spellcheck: true
        allow_source: true
        allow_internal_links: true
        link_noopener: false
        link_noreferrer: false
        target_blank: false
        semantic_elements: false
        restrict_assets: false
        sets:
          large_text_heading:
            display: 'Large text heading'
            fields:
              field_1:
                fieldset: large_text_heading
                type: partial
                display: 'Field 1'
        type: bard
        display: 'Large Text Heading'
taxonomies: true
